{{- if .Values.git.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.git.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devportal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.git.credentials.username }}
  username: {{ .Values.git.credentials.username | quote }}
  {{- end }}
  {{- if .Values.git.credentials.password }}
  password: {{ .Values.git.credentials.password | quote }}
  {{- end }}
  {{- if .Values.git.credentials.token }}
  token: {{ .Values.git.credentials.token | quote }}
  {{- end }}
{{- end }}
