# Register Geeko-Ops UI extension in Rancher Dashboard.
apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
  name: geeko-ops
  namespace: cattle-ui-plugin-system
spec:
  plugin:
    name: devportal
    version: "0.1.0"
    endpoint: "https://aeltai.github.io/rancher-devportal/extensions/devportal/0.1.0/plugin"
    noCache: true
    metadata:
      catalog.cattle.io/display-name: Geeko-Ops
      catalog.cattle.io/kube-version: ">= 1.16.0-0"
      catalog.cattle.io/rancher-version: ">= 2.10.0-0"
      catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
