replicaCount: 1

image:
  repository: ghcr.io/aeltai/rancher-devportal-operator
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: "platform-operator"

serviceAccount:
  create: true
  name: ""

platformConfig:
  # ConfigMap name created by the devportal chart (or pre-existing)
  configMapName: platform-config
  optional: false

env:
  platformNamespace: ""  # defaults to release namespace
  configPath: /etc/platform/platform.yaml
  reconcileInterval: 15s

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  allowPrivilegeEscalation: false
